---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: helm
spec:
  interval: 24h
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: metrics-server
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: helm
      interval: 12h
  values:
    apiService:
      create: true
    resources:
      limits: {}
      #  cpu: 250m
      #  memory: 256Mi
      requests: {}
      #  cpu: 250m
      #  memory: 256Mi
