apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ingress-nginx.yaml

patches:
  - patch: |
      - op: add
        path: /spec/values/extraArgs
        value:
          - --kubelet-insecure-tls=true
    target:
      kind: HelmRelease
      name: metrics-server
