---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  interval: 30m
  chart:
    spec:
      chart: istio-base
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: helm
      interval: 12h
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-discovery
  namespace: istio-system
spec:
  interval: 30m
  chart:
    spec:
      chart: istiod
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: helm
      interval: 12h
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-ingress
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: istio-ingress
spec:
  interval: 30m
  chart:
    spec:
      chart: istio-ingress
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: helm
      interval: 12h
  values: {}
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: istio
spec:
  controller: istio.io/istio-ingressgateway
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-egress
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-egress
  namespace: istio-egress
spec:
  interval: 30m
  chart:
    spec:
      chart: istio-egress
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: helm
      interval: 12h
  values: {}
